/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'JC' at '4/23/16 2:34 PM' with Gradle 2.12
 *
 * @author JC, @date 4/23/16 2:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
